"""Rich demo seed data generator for MetaReverse.

Generates a full slice of realistic data for one organization:
  - 1 organization (upsert by clerk_org_id)
  - 5 users (1 owner + 4 team members)
  - 5 batches
  - 35 pages (~7 per batch, mixed FB/IG/Threads)
  - 8 posting IDs with assignments
  - 120+ posts across many statuses
  - 90 days of page_insights per page
  - 90 days of revenue_records per page
  - team_members, invite_links, approvals

Safe to re-run: everything is keyed by UNIQUE constraints and UPSERTs.

USAGE:
    python -m scripts.generate_seed_data --org-id org_test --email demo@metareverse.xyz

The --org-id value is a Clerk-style organization identifier (string).
It maps to organizations.clerk_org_id. The underlying UUID PK is
generated by Postgres and captured for all FK inserts.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import random
import sys
import uuid
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path
from typing import Iterable

# Make `app` importable when run as `python -m scripts.generate_seed_data`
# from the backend/ directory, or as a standalone script.
BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

import psycopg2
from psycopg2.extras import RealDictCursor, execute_values

from app.core.config import get_settings
from app.core.encryption import encrypt_token


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

PAGES_PER_BATCH = 7
NUM_BATCHES = 5
NUM_POSTING_IDS = 8
NUM_EXTRA_USERS = 4
NUM_POSTS = 130
INSIGHTS_DAYS = 90
SEED_NAMESPACE = uuid.NAMESPACE_DNS

BATCH_SPECS = [
    ("Lifestyle Network", "#f97316", "Lifestyle, wellness, travel pages"),
    ("Gaming Collective", "#8b5cf6", "Gaming and esports pages"),
    ("Foodie Portfolio", "#ef4444", "Food, recipes, restaurants"),
    ("Tech & Startups", "#3b82f6", "Tech news, startup culture"),
    ("Sports Hub", "#10b981", "Sports, fitness, training"),
]

PLATFORMS = ["facebook", "instagram", "threads"]
MEDIA_TYPES = ["photo", "reel", "text"]

# Distribution weights for post status (~sum to 1.0)
POST_STATUS_WEIGHTS = [
    ("published", 0.55),
    ("queued", 0.15),
    ("draft", 0.10),
    ("pending_approval", 0.05),
    ("failed_temporary", 0.05),
    ("failed_needs_editing", 0.04),
    ("reconnect_required", 0.03),
    ("paused", 0.02),
    ("changes_requested", 0.01),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def det_uuid(*parts: str) -> uuid.UUID:
    """Deterministic UUID5 from any set of string parts."""
    return uuid.uuid5(SEED_NAMESPACE, "|".join(parts))


def pick_status(rnd: random.Random) -> str:
    r = rnd.random()
    acc = 0.0
    for name, w in POST_STATUS_WEIGHTS:
        acc += w
        if r <= acc:
            return name
    return "published"


def fake_hash(seed: str) -> str:
    return hashlib.sha256(seed.encode()).hexdigest()


# ---------------------------------------------------------------------------
# Upsert helpers
# ---------------------------------------------------------------------------


def upsert_organization(cur, clerk_org_id: str, name: str) -> uuid.UUID:
    cur.execute(
        """
        INSERT INTO organizations (clerk_org_id, name, plan)
        VALUES (%s, %s, 'free')
        ON CONFLICT (clerk_org_id) DO UPDATE
          SET name = EXCLUDED.name
        RETURNING id
        """,
        (clerk_org_id, name),
    )
    return cur.fetchone()["id"]


def upsert_user(
    cur,
    clerk_user_id: str,
    org_uuid: uuid.UUID,
    email: str,
    first_name: str,
    last_name: str,
) -> uuid.UUID:
    cur.execute(
        """
        INSERT INTO users (clerk_user_id, org_id, email, first_name, last_name, is_active)
        VALUES (%s, %s, %s, %s, %s, true)
        ON CONFLICT (clerk_user_id) DO UPDATE
          SET email = EXCLUDED.email,
              first_name = EXCLUDED.first_name,
              last_name = EXCLUDED.last_name,
              org_id = EXCLUDED.org_id
        RETURNING id
        """,
        (clerk_user_id, str(org_uuid), email, first_name, last_name),
    )
    return cur.fetchone()["id"]


def upsert_batch(
    cur, org_uuid: uuid.UUID, name: str, color: str, description: str
) -> uuid.UUID:
    cur.execute(
        """
        INSERT INTO batches (org_id, name, color, description)
        VALUES (%s, %s, %s, %s)
        ON CONFLICT (org_id, name) DO UPDATE
          SET color = EXCLUDED.color,
              description = EXCLUDED.description
        RETURNING id
        """,
        (str(org_uuid), name, color, description),
    )
    return cur.fetchone()["id"]


def upsert_posting_id(
    cur,
    org_uuid: uuid.UUID,
    facebook_user_id: str,
    name: str,
    enc_token: bytes,
    health_score: int,
    reach_28d: int,
    status: str,
) -> uuid.UUID:
    token_expires = datetime.now(timezone.utc) + timedelta(days=55)
    cur.execute(
        """
        INSERT INTO posting_ids (
            org_id, facebook_user_id, name, encrypted_access_token,
            token_expires_at, status, health_score, reach_28d, last_used_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
        ON CONFLICT (org_id, facebook_user_id) DO UPDATE
          SET name = EXCLUDED.name,
              health_score = EXCLUDED.health_score,
              reach_28d = EXCLUDED.reach_28d,
              status = EXCLUDED.status,
              last_used_at = EXCLUDED.last_used_at
        RETURNING id
        """,
        (
            str(org_uuid),
            facebook_user_id,
            name,
            psycopg2.Binary(enc_token),
            token_expires,
            status,
            health_score,
            reach_28d,
        ),
    )
    return cur.fetchone()["id"]


def upsert_page(
    cur,
    org_uuid: uuid.UUID,
    batch_id: uuid.UUID,
    platform: str,
    platform_page_id: str,
    name: str,
    enc_token: bytes,
    interval: int,
    timezone_name: str,
    status: str,
    monetization_status: str,
    require_approval: bool,
) -> uuid.UUID:
    token_expires = datetime.now(timezone.utc) + timedelta(days=45)
    cur.execute(
        """
        INSERT INTO pages (
            org_id, batch_id, platform, platform_page_id, name,
            timezone, post_interval_hours,
            active_hours_start, active_hours_end,
            require_approval, rotation_mode,
            monetization_status, status,
            encrypted_access_token, token_expires_at,
            follower_count, follower_count_updated_at,
            is_active
        )
        VALUES (%s, %s, %s, %s, %s,
                %s, %s,
                %s, %s,
                %s, 'round_robin',
                %s, %s,
                %s, %s,
                %s, now(),
                true)
        ON CONFLICT (org_id, platform, platform_page_id) DO UPDATE
          SET name = EXCLUDED.name,
              batch_id = EXCLUDED.batch_id,
              timezone = EXCLUDED.timezone,
              post_interval_hours = EXCLUDED.post_interval_hours,
              active_hours_start = EXCLUDED.active_hours_start,
              active_hours_end = EXCLUDED.active_hours_end,
              require_approval = EXCLUDED.require_approval,
              monetization_status = EXCLUDED.monetization_status,
              status = EXCLUDED.status,
              encrypted_access_token = EXCLUDED.encrypted_access_token,
              token_expires_at = EXCLUDED.token_expires_at,
              follower_count = EXCLUDED.follower_count
        RETURNING id
        """,
        (
            str(org_uuid),
            str(batch_id),
            platform,
            platform_page_id,
            name,
            timezone_name,
            interval,
            time(8, 0),
            time(22, 0),
            require_approval,
            monetization_status,
            status,
            psycopg2.Binary(enc_token),
            token_expires,
            random.randint(2_000, 500_000),
        ),
    )
    return cur.fetchone()["id"]


def upsert_page_posting_assignment(
    cur, page_id: uuid.UUID, posting_id: uuid.UUID, sort_order: int
) -> None:
    cur.execute(
        """
        INSERT INTO page_posting_id_assignments (page_id, posting_id_id, sort_order)
        VALUES (%s, %s, %s)
        ON CONFLICT (page_id, posting_id_id) DO NOTHING
        """,
        (str(page_id), str(posting_id), sort_order),
    )


def upsert_team_member(
    cur,
    org_uuid: uuid.UUID,
    user_id: uuid.UUID,
    roles: list[str],
    batch_ids: list[uuid.UUID],
    invited_by: uuid.UUID | None,
) -> None:
    cur.execute(
        """
        INSERT INTO team_members (org_id, user_id, roles, batch_ids, status, invited_by, joined_at)
        VALUES (%s, %s, %s, %s, 'active', %s, now())
        ON CONFLICT (org_id, user_id) DO UPDATE
          SET roles = EXCLUDED.roles,
              batch_ids = EXCLUDED.batch_ids,
              status = EXCLUDED.status
        """,
        (
            str(org_uuid),
            str(user_id),
            roles,
            [str(b) for b in batch_ids],
            str(invited_by) if invited_by else None,
        ),
    )


# ---------------------------------------------------------------------------
# Core seeding logic
# ---------------------------------------------------------------------------


def seed_posts_and_media(
    cur,
    org_uuid: uuid.UUID,
    clerk_org_id: str,
    pages: list[dict],
    users: list[uuid.UUID],
    posting_ids: list[uuid.UUID],
    rnd: random.Random,
    target_posts: int,
) -> int:
    """Seed NUM_POSTS posts with media and return how many we inserted/upserted."""
    now = datetime.now(timezone.utc)
    count = 0
    for i in range(target_posts):
        page = rnd.choice(pages)
        platform = page["platform"]
        media_type = rnd.choice(MEDIA_TYPES)
        status = pick_status(rnd)
        author = rnd.choice(users)
        posting_used = rnd.choice(posting_ids) if platform == "facebook" else None

        post_id = det_uuid(f"seed-{clerk_org_id}-post-{i}")
        caption_text = f"Demo post {str(post_id)[:6]} about {page['name']}"

        caption_fb = caption_text if platform == "facebook" else None
        caption_ig = caption_text if platform == "instagram" else None
        caption_th = caption_text if platform == "threads" else None

        publish_fb = platform == "facebook"
        publish_ig = platform == "instagram"
        publish_th = platform == "threads"

        scheduled_at = now - timedelta(hours=rnd.randint(-72, 24 * 30))
        published_at = scheduled_at + timedelta(minutes=rnd.randint(1, 45)) if status == "published" else None
        failed_at = now - timedelta(hours=rnd.randint(1, 48)) if status.startswith("failed") or status == "reconnect_required" else None
        failed_category = None
        failure_reason = None
        if status == "failed_temporary":
            failed_category = "temporary_issue"
            failure_reason = "Graph API returned 500"
        elif status == "failed_needs_editing":
            failed_category = "needs_editing"
            failure_reason = "Caption exceeded platform limit"
        elif status == "reconnect_required":
            failed_category = "reconnect_needed"
            failure_reason = "Access token expired mid-publish"

        file_hash = fake_hash(f"{clerk_org_id}-post-{i}") if media_type != "text" else None

        cur.execute(
            """
            INSERT INTO posts (
                id, org_id, page_id, created_by, posting_id_used,
                status, failed_category, media_type,
                caption_facebook, caption_instagram, caption_threads,
                publish_to_facebook, publish_to_instagram, publish_to_threads,
                scheduled_at, published_at, failed_at, failure_reason,
                retry_count, file_hash, is_outside_active_hours
            )
            VALUES (%s, %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s)
            ON CONFLICT (id) DO UPDATE
              SET status = EXCLUDED.status,
                  failed_category = EXCLUDED.failed_category,
                  media_type = EXCLUDED.media_type,
                  caption_facebook = EXCLUDED.caption_facebook,
                  caption_instagram = EXCLUDED.caption_instagram,
                  caption_threads = EXCLUDED.caption_threads,
                  publish_to_facebook = EXCLUDED.publish_to_facebook,
                  publish_to_instagram = EXCLUDED.publish_to_instagram,
                  publish_to_threads = EXCLUDED.publish_to_threads,
                  scheduled_at = EXCLUDED.scheduled_at,
                  published_at = EXCLUDED.published_at,
                  failed_at = EXCLUDED.failed_at,
                  failure_reason = EXCLUDED.failure_reason,
                  file_hash = EXCLUDED.file_hash
            """,
            (
                str(post_id), str(org_uuid), str(page["id"]), str(author),
                str(posting_used) if posting_used else None,
                status, failed_category, media_type,
                caption_fb, caption_ig, caption_th,
                publish_fb, publish_ig, publish_th,
                scheduled_at, published_at, failed_at, failure_reason,
                rnd.randint(0, 3), file_hash, rnd.random() < 0.1,
            ),
        )
        count += 1

        # Attach one media row for photo/reel posts
        if media_type != "text":
            media_id = det_uuid(f"seed-{clerk_org_id}-post-{i}-media-0")
            file_key = f"seed/{clerk_org_id}/{post_id}/0.jpg"
            file_url = f"https://r2.metareverse.xyz/{file_key}"
            cur.execute(
                """
                INSERT INTO post_media (
                    id, post_id, org_id, file_url, file_key, file_hash,
                    file_size, mime_type, sort_order
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                (
                    str(media_id), str(post_id), str(org_uuid),
                    file_url, file_key, file_hash,
                    1024, "image/jpeg" if media_type == "photo" else "video/mp4",
                    0,
                ),
            )

        # Approval record for a chunk of pending/reviewed posts
        if status in ("pending_approval", "changes_requested") and rnd.random() < 0.7:
            action = "approved" if status != "changes_requested" else "changes_requested"
            approval_id = det_uuid(f"seed-{clerk_org_id}-approval-{i}")
            cur.execute(
                """
                INSERT INTO approvals (id, post_id, reviewed_by, action, comment)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                (
                    str(approval_id), str(post_id), str(rnd.choice(users)), action,
                    "Looks great" if action == "approved" else "Please refresh the thumbnail",
                ),
            )

    return count


def seed_insights_and_revenue(
    cur,
    org_uuid: uuid.UUID,
    pages: list[dict],
    rnd: random.Random,
    days: int = INSIGHTS_DAYS,
) -> tuple[int, int]:
    today = date.today()
    insight_rows: list[tuple] = []
    revenue_rows: list[tuple] = []
    for page in pages:
        page_id = str(page["id"])
        for d in range(days):
            day = today - timedelta(days=d)
            views = rnd.randint(1_000, 120_000)
            viewers = int(views * rnd.uniform(0.4, 0.8))
            follows = rnd.randint(0, 400)
            unfollows = rnd.randint(0, 120)
            visits = rnd.randint(100, 9_000)
            interactions = rnd.randint(50, 12_000)
            link_clicks = rnd.randint(0, 2_500)
            video_views = rnd.randint(0, 80_000)
            watch_time = rnd.randint(0, 300_000)
            reactions = rnd.randint(10, 9_000)
            comments = rnd.randint(0, 1_200)
            shares = rnd.randint(0, 900)
            insight_rows.append((
                page_id, str(org_uuid), day, day,
                views, viewers, follows, unfollows, visits, interactions,
                link_clicks, video_views, watch_time, reactions, comments, shares,
            ))

            reels_cents = rnd.randint(0, 15_000)
            photos_cents = rnd.randint(0, 6_000)
            stories_cents = rnd.randint(0, 3_000)
            text_cents = rnd.randint(0, 800)
            total_cents = reels_cents + photos_cents + stories_cents + text_cents
            revenue_rows.append((
                page_id, str(org_uuid), day,
                total_cents, reels_cents, photos_cents, stories_cents, text_cents,
                views, "USD",
            ))

    execute_values(
        cur,
        """
        INSERT INTO page_insights (
            page_id, org_id, period_start, period_end,
            views, viewers, follows, unfollows, visits, interactions,
            link_clicks, video_views, watch_time_seconds, reactions, comments, shares
        )
        VALUES %s
        ON CONFLICT (page_id, period_start, period_end) DO UPDATE
          SET views = EXCLUDED.views,
              viewers = EXCLUDED.viewers,
              follows = EXCLUDED.follows,
              unfollows = EXCLUDED.unfollows,
              visits = EXCLUDED.visits,
              interactions = EXCLUDED.interactions,
              link_clicks = EXCLUDED.link_clicks,
              video_views = EXCLUDED.video_views,
              watch_time_seconds = EXCLUDED.watch_time_seconds,
              reactions = EXCLUDED.reactions,
              comments = EXCLUDED.comments,
              shares = EXCLUDED.shares
        """,
        insight_rows,
        page_size=500,
    )

    execute_values(
        cur,
        """
        INSERT INTO revenue_records (
            page_id, org_id, date,
            total_cents, reels_cents, photos_cents, stories_cents, text_cents,
            views, currency
        )
        VALUES %s
        ON CONFLICT (page_id, date) DO UPDATE
          SET total_cents = EXCLUDED.total_cents,
              reels_cents = EXCLUDED.reels_cents,
              photos_cents = EXCLUDED.photos_cents,
              stories_cents = EXCLUDED.stories_cents,
              text_cents = EXCLUDED.text_cents,
              views = EXCLUDED.views
        """,
        revenue_rows,
        page_size=500,
    )

    return len(insight_rows), len(revenue_rows)


def seed_invite_links(
    cur,
    org_uuid: uuid.UUID,
    clerk_org_id: str,
    invited_by: uuid.UUID,
    batch_ids: list[uuid.UUID],
) -> None:
    now = datetime.now(timezone.utc)
    demos = [
        # email, roles, status, expires_offset_days, accepted
        ("pending.approver@demo.local", ["approver"], "pending", 7, None),
        ("expired.publisher@demo.local", ["publisher"], "expired", -2, None),
        ("accepted.manager@demo.local", ["manager"], "accepted", 5, now - timedelta(days=1)),
    ]
    for idx, (email, roles, status, exp_days, accepted_at) in enumerate(demos):
        token = f"seedtok-{clerk_org_id}-{idx}-{hashlib.sha1(email.encode()).hexdigest()[:16]}"
        expires_at = now + timedelta(days=exp_days)
        cur.execute(
            """
            INSERT INTO invite_links (
                org_id, token, email, roles, batch_ids, invited_by,
                expires_at, accepted_at, status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (token) DO UPDATE
              SET status = EXCLUDED.status,
                  accepted_at = EXCLUDED.accepted_at,
                  expires_at = EXCLUDED.expires_at
            """,
            (
                str(org_uuid), token, email, roles,
                [str(b) for b in batch_ids[:2]],
                str(invited_by), expires_at, accepted_at, status,
            ),
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run(clerk_org_id: str, owner_email: str, seed: int = 42) -> dict:
    rnd = random.Random(seed)
    settings = get_settings()
    conn = psycopg2.connect(settings.database_url)
    conn.autocommit = False
    stats: dict = {}

    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            # 1. Organization
            org_uuid = upsert_organization(
                cur, clerk_org_id, name=f"Seed Org {clerk_org_id}"
            )
            stats["org_uuid"] = str(org_uuid)

            # 2. Users (owner + extras)
            owner_id = upsert_user(
                cur,
                clerk_user_id=f"clerk_{seed}_owner",
                org_uuid=org_uuid,
                email=owner_email,
                first_name="Owner",
                last_name="Zero",
            )
            extra_user_ids: list[uuid.UUID] = []
            for i in range(1, NUM_EXTRA_USERS + 1):
                uid = upsert_user(
                    cur,
                    clerk_user_id=f"clerk_{seed}_{i}",
                    org_uuid=org_uuid,
                    email=f"user{i}@demo.local",
                    first_name="User",
                    last_name=str(i),
                )
                extra_user_ids.append(uid)
            all_users = [owner_id, *extra_user_ids]
            stats["users"] = len(all_users)

            # 3. Batches
            batch_ids: list[uuid.UUID] = []
            for name, color, desc in BATCH_SPECS[:NUM_BATCHES]:
                bid = upsert_batch(cur, org_uuid, name, color, desc)
                batch_ids.append(bid)
            stats["batches"] = len(batch_ids)

            # 4. Posting IDs
            posting_ids: list[uuid.UUID] = []
            active_posting_ids: list[uuid.UUID] = []
            for i in range(NUM_POSTING_IDS):
                fb_uid = f"fb_seed_{clerk_org_id}_{i}"
                name = f"Posting ID #{i + 1}"
                enc = encrypt_token(f"mock_posting_token_{clerk_org_id}_{i}")
                # Spread health + statuses for realistic fixtures
                health = rnd.randint(25, 100)
                reach = rnd.randint(50_000, 2_500_000)
                status = "active"
                if i == NUM_POSTING_IDS - 1:
                    status = "retired"
                elif i == NUM_POSTING_IDS - 2:
                    status = "expired"
                pid = upsert_posting_id(
                    cur, org_uuid, fb_uid, name, enc, health, reach, status
                )
                posting_ids.append(pid)
                if status == "active":
                    active_posting_ids.append(pid)
            stats["posting_ids"] = len(posting_ids)

            if not active_posting_ids:
                active_posting_ids = posting_ids[: max(1, NUM_POSTING_IDS - 2)]

            # 5. Pages (~7 per batch, cycle through platforms)
            pages: list[dict] = []
            page_idx = 0
            for batch_id in batch_ids:
                for _ in range(PAGES_PER_BATCH):
                    platform = PLATFORMS[page_idx % len(PLATFORMS)]
                    platform_page_id = f"pp_{clerk_org_id}_{page_idx}"
                    page_name = f"Seed Page {page_idx + 1}"
                    enc = encrypt_token(f"mock_token_page_{page_idx}")
                    interval = rnd.choice([1, 2, 3, 4, 6, 8])
                    tz = rnd.choice(
                        ["UTC", "America/New_York", "Europe/London", "Asia/Karachi"]
                    )
                    # Spread statuses a bit
                    if page_idx % 15 == 0:
                        pstatus = "token_expiring"
                    elif page_idx % 23 == 0:
                        pstatus = "token_expired"
                    elif page_idx % 31 == 0:
                        pstatus = "paused"
                    else:
                        pstatus = "ready"
                    mon = rnd.choice(["enrolled", "not_enrolled", "ineligible"])
                    require_approval = rnd.random() < 0.3
                    pid_row = upsert_page(
                        cur,
                        org_uuid,
                        batch_id,
                        platform,
                        platform_page_id,
                        page_name,
                        enc,
                        interval,
                        tz,
                        pstatus,
                        mon,
                        require_approval,
                    )
                    pages.append({
                        "id": pid_row,
                        "platform": platform,
                        "name": page_name,
                        "batch_id": batch_id,
                    })
                    page_idx += 1
            stats["pages"] = len(pages)

            # 6. Assign 2 posting IDs per page (round robin) for FB-connected pages
            for idx, page in enumerate(pages):
                pool = active_posting_ids or posting_ids
                primary = pool[idx % len(pool)]
                secondary = pool[(idx + 1) % len(pool)]
                upsert_page_posting_assignment(cur, page["id"], primary, 0)
                if secondary != primary:
                    upsert_page_posting_assignment(cur, page["id"], secondary, 1)

            # 7. Team memberships
            # Owner covers everything; others get subsets of batches + role mix
            upsert_team_member(cur, org_uuid, owner_id, ["owner"], batch_ids, None)
            role_rotation = [
                ["manager"],
                ["publisher"],
                ["approver"],
                ["analyst", "publisher"],
            ]
            for i, uid in enumerate(extra_user_ids):
                roles = role_rotation[i % len(role_rotation)]
                subset = batch_ids[: max(1, (i % len(batch_ids)) + 1)]
                upsert_team_member(cur, org_uuid, uid, roles, subset, owner_id)

            # 8. Posts + media + approvals
            stats["posts"] = seed_posts_and_media(
                cur,
                org_uuid,
                clerk_org_id,
                pages,
                all_users,
                posting_ids,
                rnd,
                target_posts=NUM_POSTS,
            )

            # 9. Page insights + revenue (90 days each)
            insight_n, revenue_n = seed_insights_and_revenue(
                cur, org_uuid, pages, rnd, days=INSIGHTS_DAYS
            )
            stats["page_insights"] = insight_n
            stats["revenue_records"] = revenue_n

            # 10. Invite links
            seed_invite_links(cur, org_uuid, clerk_org_id, owner_id, batch_ids)

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    return stats


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate rich demo seed data for MetaReverse. "
            "The --org-id value is a Clerk-style string identifier and is stored "
            "as organizations.clerk_org_id. The internal UUID PK is generated by "
            "Postgres and used for all downstream FK inserts."
        )
    )
    parser.add_argument(
        "--org-id",
        required=True,
        help="Clerk-style org identifier (string). Maps to organizations.clerk_org_id.",
    )
    parser.add_argument(
        "--email",
        required=True,
        help="Owner user's email address.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for deterministic-ish output (default: 42).",
    )
    args = parser.parse_args(argv)

    stats = run(args.org_id, args.email, seed=args.seed)
    print("[seed] done:", stats)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
